package slimeknights.tconstruct.tools;

import slimeknights.tconstruct.library.traits.*;
import net.minecraft.entity.monster.*;
import slimeknights.tconstruct.world.entity.*;
import slimeknights.tconstruct.tools.traits.*;

public class TinkerTraits
{
    public static final AbstractTrait alien;
    public static final AbstractTrait aquadynamic;
    public static final AbstractTrait aridiculous;
    public static final AbstractTrait autosmelt;
    public static final AbstractTrait baconlicious;
    public static final AbstractTrait cheap;
    public static final AbstractTrait cheapskate;
    public static final AbstractTrait coldblooded;
    public static final AbstractTrait crude;
    public static final AbstractTrait crude2;
    public static final AbstractTrait crumbling;
    public static final AbstractTrait dense;
    public static final AbstractTrait depthdigger;
    public static final AbstractTrait duritos;
    public static final AbstractTrait ecological;
    public static final AbstractTrait enderference;
    public static final AbstractTrait established;
    public static final AbstractTrait flammable;
    public static final AbstractTrait fractured;
    public static final AbstractTrait heavy;
    public static final AbstractTrait hellish;
    public static final AbstractTrait holy;
    public static final AbstractTrait insatiable;
    public static final AbstractTrait jagged;
    public static final AbstractTrait lightweight;
    public static final AbstractTrait magnetic;
    public static final AbstractTrait magnetic2;
    public static final AbstractTrait momentum;
    public static final AbstractTrait petramor;
    public static final AbstractTrait poisonous;
    public static final AbstractTrait prickly;
    public static final AbstractTrait sharp;
    public static final AbstractTrait shocking;
    public static final AbstractTrait slimeyGreen;
    public static final AbstractTrait slimeyBlue;
    public static final AbstractTrait spiky;
    public static final AbstractTrait splintering;
    public static final AbstractTrait splinters;
    public static final AbstractTrait squeaky;
    public static final AbstractTrait superheat;
    public static final AbstractTrait stiff;
    public static final AbstractTrait stonebound;
    public static final AbstractTrait tasty;
    public static final AbstractTrait unnatural;
    public static final AbstractTrait writable;
    public static final AbstractTrait writable2;
    public static final AbstractTrait breakable;
    public static final AbstractTrait endspeed;
    public static final AbstractTrait freezing;
    public static final AbstractTrait hovering;
    public static final AbstractTrait splitting;
    
    static {
        alien = new TraitAlien();
        aquadynamic = new TraitAquadynamic();
        aridiculous = new TraitAridiculous();
        autosmelt = new TraitAutosmelt();
        baconlicious = new TraitBaconlicious();
        cheap = new TraitCheap();
        cheapskate = new TraitCheapskate();
        coldblooded = new TraitColdblooded();
        crude = new TraitCrude(1);
        crude2 = new TraitCrude(2);
        crumbling = new TraitCrumbling();
        dense = new TraitDense();
        depthdigger = new TraitDepthdigger();
        duritos = new TraitDuritos();
        ecological = new TraitEcological();
        enderference = new TraitEnderference();
        established = new TraitEstablished();
        flammable = new TraitFlammable();
        fractured = new TraitBonusDamage("fractured", 1.5f);
        heavy = new TraitHeavy();
        hellish = new TraitHellish();
        holy = new TraitHoly();
        insatiable = new TraitInsatiable();
        jagged = new TraitJagged();
        lightweight = new TraitLightweight();
        magnetic = new TraitMagnetic(1);
        magnetic2 = new TraitMagnetic(2);
        momentum = new TraitMomentum();
        petramor = new TraitPetramor();
        poisonous = new TraitPoisonous();
        prickly = new TraitPrickly();
        sharp = new TraitSharp();
        shocking = new TraitShocking();
        slimeyGreen = new TraitSlimey("green", EntitySlime.class);
        slimeyBlue = new TraitSlimey("blue", EntityBlueSlime.class);
        spiky = new TraitSpiky();
        splintering = new TraitSplintering();
        splinters = new TraitSplinters();
        squeaky = new TraitSqueaky();
        superheat = new TraitSuperheat();
        stiff = new TraitStiff();
        stonebound = new TraitStonebound();
        tasty = new TraitTasty();
        unnatural = new TraitUnnatural();
        writable = new TraitWritable(1);
        writable2 = new TraitWritable(2);
        breakable = new TraitBreakable();
        endspeed = new TraitEndspeed();
        freezing = new TraitFreezing();
        hovering = new TraitHovering();
        splitting = new TraitSplitting();
    }
}
